"""Peak-distance export and JSON/CSV interchange for Sparse IQ H5 recordings.

Shared by the standalone CLI exporter and the heatmap alignment GUI importer.
"""

from __future__ import annotations

import json
from dataclasses import dataclass
from datetime import datetime, timedelta
from pathlib import Path
from typing import Any, Literal

import numpy as np
import pandas as pd
from sparse_iq_heatmap_common import (
    HeatmapAxes,
    HeatmapRecord,
    distance_velocity_map,
    elapsed_time_seconds,
    heatmap_axes,
    load_heatmap_record,
    resolve_selection_indices,
    select_frame_indices,
    select_subsweep,
)


DEFAULT_PEAK_THRESHOLD = 650.0
PEAK_DISTANCE_FORMAT = "acconeer_peak_distances"
PEAK_DISTANCE_VERSION = 1

STATUS_DETECTED: Literal["detected"] = "detected"
STATUS_NO_DETECTION: Literal["no_detection"] = "no_detection"

INVALID_PEAK_DISTANCE_JSON_MESSAGE = (
    "This is not a peak-distance JSON file generated by peak-distances."
)

REDUCED_PEAK_DISTANCE_CSV_COLUMNS: tuple[str, ...] = (
    "frame_index",
    "source_tick",
    "time_s",
    "absolute_time",
    "status",
    "peak_distance_m",
    "candidate_peak_distance_m",
    "peak_strength",
)


@dataclass(frozen=True)
class PeakDistanceExportConfig:
    h5_path: Path
    session_idx: int
    group_idx: int
    entry_idx: int
    subsweep_idx: int
    threshold: float = DEFAULT_PEAK_THRESHOLD
    every_n: int = 1
    max_frames: int | None = None


@dataclass(frozen=True)
class ZeroVelocityBin:
    bin_index: int
    velocity_m_s: float


@dataclass(frozen=True)
class FramePeakMeasurement:
    frame_index: int
    source_tick: int
    time_s: float
    absolute_time: str | None
    status: str
    peak_distance_m: float | None
    candidate_peak_distance_m: float
    peak_strength: float


@dataclass(frozen=True)
class PeakDistanceMetadata:
    source_path: str
    source_name: str
    session_index: int
    group_index: int
    entry_index: int
    sensor_id: int
    subsweep_index: int
    source_frame_count: int
    source_duration_s: float
    ticks_per_second: int
    threshold: float
    zero_velocity_bin_index: int
    zero_velocity_m_s: float


@dataclass(frozen=True)
class PeakDistanceExportResult:
    metadata: PeakDistanceMetadata
    measurements: tuple[FramePeakMeasurement, ...]


@dataclass(frozen=True)
class LoadedPeakDistanceDatasource:
    path: Path
    metadata: PeakDistanceMetadata
    measurements: tuple[FramePeakMeasurement, ...]


@dataclass
class PeakDistanceDatasourceSettings:
    path: str = ""
    visible: bool = True


class PeakDistanceJsonImportError(ValueError):
    """Raised when a file is not a canonical peak-distance JSON export."""

    def __init__(self, detail: str) -> None:
        self.detail = detail.strip()
        super().__init__(self.user_message())

    @property
    def primary_message(self) -> str:
        return INVALID_PEAK_DISTANCE_JSON_MESSAGE

    def user_message(self) -> str:
        if self.detail:
            return f"{self.primary_message}\n\n{self.detail}"
        return self.primary_message


def _invalid_peak_distance_json_error(detail: str) -> PeakDistanceJsonImportError:
    return PeakDistanceJsonImportError(detail)


def _peak_distance_format_mismatch_detail(payload: dict[str, Any]) -> str:
    actual_format = payload.get("format")
    if "format" not in payload or actual_format is None:
        return (
            "Use a JSON file exported with `hatch run app:peak-distances`, not another "
            "JSON file."
        )
    return (
        f"The file format is {actual_format!r}, not the peak-distances export "
        f"({PEAK_DISTANCE_FORMAT!r})."
    )


def _peak_distance_version_mismatch_detail(payload: dict[str, Any]) -> str:
    actual_version = payload.get("version")
    if actual_version is None:
        return f"Missing export version; expected version {PEAK_DISTANCE_VERSION}."
    return (
        f"Unsupported export version {actual_version!r}; "
        f"expected version {PEAK_DISTANCE_VERSION}."
    )


def zero_velocity_bin_index(velocities_m_s: np.ndarray) -> ZeroVelocityBin:
    if len(velocities_m_s) == 0:
        msg = "Velocity axis is empty."
        raise ValueError(msg)
    bin_index = int(np.argmin(np.abs(velocities_m_s)))
    return ZeroVelocityBin(bin_index=bin_index, velocity_m_s=float(velocities_m_s[bin_index]))


def strongest_peak_in_zero_velocity_slice(
    dvm: np.ndarray,
    distances_m: np.ndarray,
    *,
    zero_velocity_bin: int,
    threshold: float,
) -> tuple[str, float, float | None, float]:
    if dvm.ndim != 2:
        msg = f"Expected 2-D distance/velocity map, got shape {dvm.shape!r}."
        raise ValueError(msg)
    # `distance_velocity_map` FFTs along slow time (axis 0 of subframe), so rows are velocity
    # bins and columns are distance bins — matching heatmap imshow (x=distance, y=velocity).
    if zero_velocity_bin < 0 or zero_velocity_bin >= dvm.shape[0]:
        msg = f"Zero-velocity bin {zero_velocity_bin} is outside axis size {dvm.shape[0]}."
        raise ValueError(msg)

    slice_strengths = dvm[zero_velocity_bin, :]
    peak_bin = int(np.argmax(slice_strengths))
    peak_strength = float(slice_strengths[peak_bin])
    candidate_peak_distance_m = float(distances_m[peak_bin])
    if peak_strength <= threshold:
        return STATUS_NO_DETECTION, candidate_peak_distance_m, None, peak_strength

    return STATUS_DETECTED, candidate_peak_distance_m, candidate_peak_distance_m, peak_strength


def _absolute_time_value(record_timestamp: str, elapsed_s: float) -> str | None:
    try:
        absolute_time = datetime.fromisoformat(record_timestamp) + timedelta(seconds=elapsed_s)
        return absolute_time.isoformat(timespec="milliseconds")
    except ValueError:
        return None


def analyze_heatmap_record(
    heatmap_record: HeatmapRecord,
    *,
    h5_path: Path,
    subsweep_idx: int,
    frame_indices: list[int],
    threshold: float,
) -> PeakDistanceExportResult:
    subsweep = select_subsweep(heatmap_record, subsweep_idx)
    axes = heatmap_axes(heatmap_record.metadata, heatmap_record.sensor_config, subsweep)
    zero_velocity = zero_velocity_bin_index(axes.velocities_m_s)

    measurements: list[FramePeakMeasurement] = []
    for frame_index in frame_indices:
        dvm = distance_velocity_map(heatmap_record.results[frame_index].subframes[subsweep_idx])
        status, candidate_peak_distance_m, peak_distance_m, peak_strength = (
            strongest_peak_in_zero_velocity_slice(
                dvm,
                axes.distances_m,
                zero_velocity_bin=zero_velocity.bin_index,
                threshold=threshold,
            )
        )
        elapsed_s = elapsed_time_seconds(
            heatmap_record.ticks,
            heatmap_record.ticks_per_second,
            frame_index,
        )
        measurements.append(
            FramePeakMeasurement(
                frame_index=frame_index,
                source_tick=int(heatmap_record.ticks[frame_index]),
                time_s=elapsed_s,
                absolute_time=_absolute_time_value(
                    heatmap_record.record_timestamp,
                    elapsed_s,
                ),
                status=status,
                peak_distance_m=peak_distance_m,
                candidate_peak_distance_m=candidate_peak_distance_m,
                peak_strength=peak_strength,
            )
        )

    resolved_h5_path = h5_path.resolve()
    metadata = PeakDistanceMetadata(
        source_path=str(resolved_h5_path),
        source_name=resolved_h5_path.name,
        session_index=heatmap_record.session_idx,
        group_index=heatmap_record.group_idx,
        entry_index=heatmap_record.entry_idx,
        sensor_id=heatmap_record.sensor_id,
        subsweep_index=subsweep_idx,
        source_frame_count=len(heatmap_record.results),
        source_duration_s=heatmap_record.duration_s,
        ticks_per_second=heatmap_record.ticks_per_second,
        threshold=threshold,
        zero_velocity_bin_index=zero_velocity.bin_index,
        zero_velocity_m_s=zero_velocity.velocity_m_s,
    )
    return PeakDistanceExportResult(metadata=metadata, measurements=tuple(measurements))


def export_peak_distances(config: PeakDistanceExportConfig) -> PeakDistanceExportResult:
    heatmap_record = load_heatmap_record(
        config.h5_path,
        config.session_idx,
        config.group_idx,
        config.entry_idx,
    )
    try:
        frame_indices = select_frame_indices(
            heatmap_record.results,
            max(config.every_n, 1),
            config.max_frames,
        )
        return analyze_heatmap_record(
            heatmap_record,
            h5_path=config.h5_path,
            subsweep_idx=config.subsweep_idx,
            frame_indices=frame_indices,
            threshold=config.threshold,
        )
    finally:
        heatmap_record.close()


def peak_distance_document(result: PeakDistanceExportResult) -> dict[str, Any]:
    return {
        "format": PEAK_DISTANCE_FORMAT,
        "version": PEAK_DISTANCE_VERSION,
        "metadata": {
            "source_path": result.metadata.source_path,
            "source_name": result.metadata.source_name,
            "session_index": result.metadata.session_index,
            "group_index": result.metadata.group_index,
            "entry_index": result.metadata.entry_index,
            "sensor_id": result.metadata.sensor_id,
            "subsweep_index": result.metadata.subsweep_index,
            "source_frame_count": result.metadata.source_frame_count,
            "source_duration_s": result.metadata.source_duration_s,
            "ticks_per_second": result.metadata.ticks_per_second,
            "threshold": result.metadata.threshold,
            "zero_velocity_bin_index": result.metadata.zero_velocity_bin_index,
            "zero_velocity_m_s": result.metadata.zero_velocity_m_s,
        },
        "measurements": [
            {
                "frame_index": measurement.frame_index,
                "source_tick": measurement.source_tick,
                "time_s": measurement.time_s,
                "absolute_time": measurement.absolute_time,
                "status": measurement.status,
                "peak_distance_m": measurement.peak_distance_m,
                "candidate_peak_distance_m": measurement.candidate_peak_distance_m,
                "peak_strength": measurement.peak_strength,
            }
            for measurement in result.measurements
        ],
    }


def write_peak_distance_json(result: PeakDistanceExportResult, output_path: Path) -> None:
    output_path.parent.mkdir(parents=True, exist_ok=True)
    try:
        output_path.write_text(
            json.dumps(peak_distance_document(result), indent=2),
            encoding="utf-8",
        )
    except OSError as exc:
        msg = f"Could not write peak-distance JSON to {output_path}: {exc}"
        raise OSError(msg) from exc


def _metadata_from_dict(payload: dict[str, Any]) -> PeakDistanceMetadata:
    required_keys = (
        "source_path",
        "source_name",
        "session_index",
        "group_index",
        "entry_index",
        "sensor_id",
        "subsweep_index",
        "source_frame_count",
        "source_duration_s",
        "ticks_per_second",
        "threshold",
        "zero_velocity_bin_index",
        "zero_velocity_m_s",
    )
    missing = [key for key in required_keys if key not in payload]
    if missing:
        msg = f"Metadata is missing required keys: {', '.join(missing)}."
        raise _invalid_peak_distance_json_error(msg)
    return PeakDistanceMetadata(
        source_path=str(payload["source_path"]),
        source_name=str(payload["source_name"]),
        session_index=int(payload["session_index"]),
        group_index=int(payload["group_index"]),
        entry_index=int(payload["entry_index"]),
        sensor_id=int(payload["sensor_id"]),
        subsweep_index=int(payload["subsweep_index"]),
        source_frame_count=int(payload["source_frame_count"]),
        source_duration_s=float(payload["source_duration_s"]),
        ticks_per_second=int(payload["ticks_per_second"]),
        threshold=float(payload["threshold"]),
        zero_velocity_bin_index=int(payload["zero_velocity_bin_index"]),
        zero_velocity_m_s=float(payload["zero_velocity_m_s"]),
    )


def _measurement_from_dict(payload: dict[str, Any]) -> FramePeakMeasurement:
    required_keys = (
        "frame_index",
        "source_tick",
        "time_s",
        "absolute_time",
        "status",
        "peak_distance_m",
        "candidate_peak_distance_m",
        "peak_strength",
    )
    missing = [key for key in required_keys if key not in payload]
    if missing:
        msg = f"A measurement object is missing required keys: {', '.join(missing)}."
        raise _invalid_peak_distance_json_error(msg)

    peak_distance_m = payload["peak_distance_m"]
    absolute_time = payload["absolute_time"]
    return FramePeakMeasurement(
        frame_index=int(payload["frame_index"]),
        source_tick=int(payload["source_tick"]),
        time_s=float(payload["time_s"]),
        absolute_time=None if absolute_time is None else str(absolute_time),
        status=str(payload["status"]),
        peak_distance_m=None if peak_distance_m is None else float(peak_distance_m),
        candidate_peak_distance_m=float(payload["candidate_peak_distance_m"]),
        peak_strength=float(payload["peak_strength"]),
    )


def load_peak_distance_json(json_path: Path) -> LoadedPeakDistanceDatasource:
    if json_path.suffix.lower() == ".csv":
        msg = (
            "Reduced CSV peak-distance exports cannot be imported into the heatmap alignment "
            "GUI. Use the canonical JSON export from `hatch run app:peak-distances`."
        )
        raise ValueError(msg)

    try:
        payload = json.loads(json_path.read_text(encoding="utf-8"))
    except OSError as exc:
        msg = f"Could not read peak-distance JSON {json_path}: {exc}"
        raise OSError(msg) from exc
    except json.JSONDecodeError as exc:
        msg = f"JSON parse error: {exc}"
        raise _invalid_peak_distance_json_error(msg) from exc

    if not isinstance(payload, dict):
        msg = f"Expected a JSON object at the top level, got {type(payload).__name__}."
        raise _invalid_peak_distance_json_error(msg)

    if payload.get("format") != PEAK_DISTANCE_FORMAT:
        raise _invalid_peak_distance_json_error(_peak_distance_format_mismatch_detail(payload))
    if payload.get("version") != PEAK_DISTANCE_VERSION:
        raise _invalid_peak_distance_json_error(_peak_distance_version_mismatch_detail(payload))

    metadata_payload = payload.get("metadata")
    if not isinstance(metadata_payload, dict):
        msg = "Missing metadata object."
        raise _invalid_peak_distance_json_error(msg)

    measurements_payload = payload.get("measurements")
    if not isinstance(measurements_payload, list):
        msg = "Missing measurements array."
        raise _invalid_peak_distance_json_error(msg)
    if len(measurements_payload) == 0:
        msg = "Measurements array is empty."
        raise _invalid_peak_distance_json_error(msg)

    metadata = _metadata_from_dict(metadata_payload)
    measurements = tuple(
        _measurement_from_dict(item) for item in measurements_payload if isinstance(item, dict)
    )
    if len(measurements) != len(measurements_payload):
        msg = "Every measurements entry must be a JSON object."
        raise _invalid_peak_distance_json_error(msg)

    return LoadedPeakDistanceDatasource(
        path=json_path,
        metadata=metadata,
        measurements=measurements,
    )


def reduced_measurements_to_dataframe(result: PeakDistanceExportResult) -> pd.DataFrame:
    rows: list[dict[str, object]] = []
    for measurement in result.measurements:
        rows.append(
            {
                "frame_index": measurement.frame_index,
                "source_tick": measurement.source_tick,
                "time_s": measurement.time_s,
                "absolute_time": measurement.absolute_time or "",
                "status": measurement.status,
                "peak_distance_m": measurement.peak_distance_m,
                "candidate_peak_distance_m": measurement.candidate_peak_distance_m,
                "peak_strength": measurement.peak_strength,
            }
        )
    return pd.DataFrame(rows, columns=list(REDUCED_PEAK_DISTANCE_CSV_COLUMNS))


def write_peak_distance_csv(result: PeakDistanceExportResult, output_path: Path) -> None:
    output_path.parent.mkdir(parents=True, exist_ok=True)
    try:
        reduced_measurements_to_dataframe(result).to_csv(output_path, index=False)
    except OSError as exc:
        msg = f"Could not write reduced peak-distance CSV to {output_path}: {exc}"
        raise OSError(msg) from exc


def validate_peak_distance_import(
    datasource: LoadedPeakDistanceDatasource,
    *,
    heatmap_frame_count: int,
    heatmap_duration_s: float,
    heatmap_path: Path | None,
    session_idx: int | None,
    group_idx: int | None,
    entry_idx: int | None,
    subsweep_idx: int | None,
    sensor_id: int | None,
) -> list[str]:
    warnings: list[str] = []
    metadata = datasource.metadata

    if len(datasource.measurements) != heatmap_frame_count:
        msg = (
            f"Peak-distance JSON has {len(datasource.measurements)} measurements but the loaded "
            f"H5 recording has {heatmap_frame_count} frames."
        )
        raise ValueError(msg)

    if datasource.measurements:
        last_time_s = max(measurement.time_s for measurement in datasource.measurements)
        if last_time_s > heatmap_duration_s + 1e-3:
            msg = (
                f"Peak-distance JSON elapsed time ({last_time_s:.3f} s) exceeds the loaded H5 "
                f"duration ({heatmap_duration_s:.3f} s)."
            )
            raise ValueError(msg)

    if heatmap_path is not None:
        resolved_h5 = heatmap_path.resolve()
        json_source = Path(metadata.source_path)
        try:
            paths_match = json_source.resolve() == resolved_h5
        except OSError:
            paths_match = False
        if not paths_match:
            warnings.append(
                "Peak-distance JSON source_path does not match the loaded H5 file path."
            )
        if metadata.source_name != heatmap_path.name:
            warnings.append(
                "Peak-distance JSON source_name does not match the loaded H5 file name."
            )

    if session_idx is not None and metadata.session_index != session_idx:
        warnings.append("Peak-distance JSON session_index does not match the loaded H5 session.")
    if group_idx is not None and metadata.group_index != group_idx:
        warnings.append("Peak-distance JSON group_index does not match the loaded H5 group.")
    if entry_idx is not None and metadata.entry_index != entry_idx:
        warnings.append("Peak-distance JSON entry_index does not match the loaded H5 entry.")
    if subsweep_idx is not None and metadata.subsweep_index != subsweep_idx:
        warnings.append("Peak-distance JSON subsweep_index does not match the loaded H5 subsweep.")
    if sensor_id is not None and metadata.sensor_id != sensor_id:
        warnings.append("Peak-distance JSON sensor_id does not match the loaded H5 sensor.")

    return warnings


def measurement_for_frame(
    datasource: LoadedPeakDistanceDatasource,
    frame_index: int,
) -> FramePeakMeasurement | None:
    for measurement in datasource.measurements:
        if measurement.frame_index == frame_index:
            return measurement
    return None


def annotate_heatmap_rgb_with_peak(
    frame_rgb: np.ndarray,
    *,
    axes: HeatmapAxes,
    peak_distance_m: float,
    zero_velocity_m_s: float,
) -> np.ndarray:
    if frame_rgb.ndim != 3 or frame_rgb.shape[2] != 3:
        msg = f"Expected RGB frame with shape (H, W, 3), got {frame_rgb.shape!r}."
        raise ValueError(msg)

    annotated = frame_rgb.copy()
    height, width = annotated.shape[:2]
    distance_step = np.median(np.diff(axes.distances_m)) if len(axes.distances_m) > 1 else 1.0
    x_min = float(axes.distances_m[0] - 0.5 * distance_step)
    x_max = float(axes.distances_m[-1] + 0.5 * distance_step)
    y_min = float(axes.velocities_m_s[0] - 0.5 * axes.velocity_resolution)
    y_max = float(axes.velocities_m_s[-1] + 0.5 * axes.velocity_resolution)

    if x_max <= x_min or y_max <= y_min:
        return annotated

    x_ratio = (peak_distance_m - x_min) / (x_max - x_min)
    y_ratio = (zero_velocity_m_s - y_min) / (y_max - y_min)
    column = int(round(np.clip(x_ratio, 0.0, 1.0) * (width - 1)))
    row = int(round(np.clip(y_ratio, 0.0, 1.0) * (height - 1)))

    marker_radius = max(2, min(width, height) // 80)
    row_min = max(0, row - marker_radius)
    row_max = min(height, row + marker_radius + 1)
    column_min = max(0, column - marker_radius)
    column_max = min(width, column + marker_radius + 1)
    annotated[row_min:row_max, column_min:column_max] = np.array([255, 64, 64], dtype=np.uint8)

    line_half_width = max(1, marker_radius // 2)
    line_left = max(0, column - line_half_width)
    line_right = min(width, column + line_half_width + 1)
    annotated[:, line_left:line_right] = np.maximum(
        annotated[:, line_left:line_right],
        np.array([255, 220, 64], dtype=np.uint8),
    )
    return np.ascontiguousarray(annotated)


def resolve_peak_distance_export_indices(
    config: PeakDistanceExportConfig,
) -> PeakDistanceExportConfig:
    session_idx, group_idx, entry_idx, subsweep_idx = resolve_selection_indices(
        h5_path=config.h5_path,
        session_idx=config.session_idx,
        group_idx=config.group_idx,
        entry_idx=config.entry_idx,
        subsweep_idx=config.subsweep_idx,
    )
    return PeakDistanceExportConfig(
        h5_path=config.h5_path,
        session_idx=session_idx,
        group_idx=group_idx,
        entry_idx=entry_idx,
        subsweep_idx=subsweep_idx,
        threshold=config.threshold,
        every_n=config.every_n,
        max_frames=config.max_frames,
    )
